mongo:
  image: mongo:3.0.4
  command: mongod --smallfiles --quiet
  volumes:
    - ./volumes/mongo:/data/db
  ports:
    - "27017:27017"

api:
  build: .
  links:
    - mongo
  ports:
    - "3000:3000"
  environment:
    - MONGO_URL=mongodb://mongo:27017
    - NODE_ENV=production
